# Replace AKfycbwWmUNijCzjPlejiMZhLz_l53nebJuOhsX0tbxUgZmWU4r3R9FKaM4A8Y4nd4Kmca_gpg with your Apps Script deployment ID.
[[redirects]]
  from = "/api/initial-data"
  to = "https://script.google.com/macros/s/AKfycbwWmUNijCzjPlejiMZhLz_l53nebJuOhsX0tbxUgZmWU4r3R9FKaM4A8Y4nd4Kmca_gpg/exec?action=initial-data"
  status = 200
  force = true

[[redirects]]
  from = "/api/invoice"
  to = "https://script.google.com/macros/s/AKfycbwWmUNijCzjPlejiMZhLz_l53nebJuOhsX0tbxUgZmWU4r3R9FKaM4A8Y4nd4Kmca_gpg/exec?action=invoice"
  status = 200
  force = true

[[redirects]]
  from = "/api/save-invoice"
  to = "https://script.google.com/macros/s/AKfycbwWmUNijCzjPlejiMZhLz_l53nebJuOhsX0tbxUgZmWU4r3R9FKaM4A8Y4nd4Kmca_gpg/exec?action=save-invoice"
  status = 200
  force = true
